name: geoflutterfire2
description: GeoFlutterFire2 is an open-source library that allows you to store and query firestore documents based on their geographic location.
version: 2.3.15
homepage: https://github.com/KumaloWilson/GeoFlutterFire2

environment:
  sdk: "^3.6.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^4.4.4
  rxdart: ^0.27.7

dev_dependencies:
  flutter_test:
    sdk: flutter
